live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/{kanagawa_wave}.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#dcd7ba"
background = "#0E0E18"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "None"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 0
y = 0
